### ISSUE TITLE
I started writing things on pre 0.4 Fountain, all examples need upadating 

### ISSUE THREAD

**Issue by hornc** [hornc/Fountain-expts#1]
I managed to start looking at this just (hours?) before a version update, and now my examples don't work :)

```
Updating 389450e..29fb426

```
is the 'it worked' -> 'doesn't work now' transition.

I'll figure out what needs to change.

Looks like I am relying on catch-all pre-conditions, which used to work, now doesn't in 0.4.

```
Round<a, rounds, drop> ::=
    (
         <. drop = 3 .> Drop<a>
       | <. drop = 7 .>  Catch<a> <. drop -= 7 .>
       | Catch<a>                  
    ) #10
;
```

Error msg: `fountain.exe: No pre-condition present on these Alt choices: (Catch<a>)`

Now that I check official examples, I'm not seeing a catch all pattern. I may have just made that up as a technique because it seemed to work.

**Comment by hornc** [comment]
hmmm this looks like a feature, not a bug: https://github.com/catseye/Fountain/commit/5f9bd346255b42160ce2b5a6dbe0f7790354c48f

As I was suspecting.

**Comment by hornc** [comment]
https://github.com/hornc/Fountain-expts/commit/d5d8f33001c321cddc0bcb781a67f217d68272b9

Shows changes I made to explicitly cover either side of an equal constraint to make it generate the same result as pre 0.4. While not having the ambiguity makes sense, it seems a lot more verbose, and I've been forced to state two identical branches because there isn't a `!=`

 I liked the idea that the last unconstrained option was a catch all that is just the `NOT` of all of the others combined. I think that's unambiguous too, but maybe there is a catch?

@cpressey I realize I'm picking this up while you are still working on it and it's in early stages and all very bleeding edge, but if you want to see an example of someone trying to use this in the wild, feel free to have a look. I'm trying to follow along and make use of Fountain for mainly generation purposes. I wanted to take up the challenge of implementing a PRNG _in_ Fountain, but there's quite a bit to play with in general.

**Comment by hornc** [comment]
Closing. I seem to have the hang of ensuring every alt is covered. It seemed overly verbose at first, but I'm used to it now. Haven't thought it through fully, but it seems reasonable enough to expect explicit alt coverage. 

#2 looks like it'll be the next update problem.

**Comment by cpressey** [comment]
Hi!

I am definitely impressed that you wrote a PRNG considering the absolutely minimal support Fountain currently has for arithmetic operations.

I considered writing a PRNG in Fountain too, but I don't think I'd dare without arithmetic support.  I was also put off by the fact that one would need to "thread" the PRNG state up and down the grammar -- it's doable, but a bit clumsy.  I was actually considering something like a monad to carry along this state in a more implicit way, though I have only the vaguest idea of how that would work given that Fountain is not a functional programming language.

Unfortunately I can't say I have a strong and clear idea of what each and every feature in Fountain should be or do.  The upgrade from 0.3 to 0.4 wasn't even something I planned out in detail; it was partly a reaction to my own poor understanding of its behaviour during backtracking.

My main reason for `|` to not be an ordered choice operator is that it's mathmatically nicer for it to be unordered.  I still haven't decided how to approach random choice, but one possibility is to choose randomly from all the allowable alternatives, and that doesn't really line up with it having an order.  The constriction to having exactly one alternative be allowable is to keep things efficient by default; if going in the direction the idea would be to notate somehow that random choice is OK during generation.

I would be open to an `else` keyword, which could be put on one of the alternatives, and would be shorthand for "not A and not B and not C" (where A, B, C are the other alternatives).  But, again, I don't have a full idea of how negation should work yet, so that's a bit of a blocker.  Though obviously the negation of `a >= b` would be `b > a` so this could at least be implemented to a degree.
